# Generated by Django 2.1.2 on 2018-10-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=25)),
                ('LastName', models.CharField(max_length=25)),
                ('MobileNumber', models.CharField(max_length=10)),
                ('ResidentailAddress', models.CharField(max_length=25)),
                ('City', models.CharField(max_length=25)),
                ('State', models.CharField(max_length=25)),
                ('Pincode', models.CharField(max_length=7)),
                ('DateOfBirth', models.DateField()),
                ('Summary', models.CharField(max_length=100)),
                ('EducationSummary', models.CharField(max_length=100)),
                ('CollegeName', models.CharField(max_length=25)),
                ('Cgpa', models.CharField(max_length=25)),
                ('JobTitle', models.CharField(max_length=25)),
                ('Company', models.CharField(max_length=25)),
                ('Location', models.CharField(max_length=25)),
                ('WorkSummary', models.CharField(max_length=100)),
                ('HobbiesSummary', models.CharField(max_length=100)),
                ('Skill', models.CharField(max_length=25)),
                ('SkillSummary', models.CharField(max_length=100)),
                ('Language', models.CharField(max_length=25)),
                ('RefName', models.CharField(max_length=25)),
                ('RefNo', models.CharField(max_length=25)),
                ('RefAdd', models.CharField(max_length=25)),
                ('RefEmail', models.EmailField(max_length=25)),
                ('RefCompany', models.CharField(max_length=25)),
            ],
        ),
    ]
